name: Magento installation
on: [push]
defaults:
  run:
    shell: bash
jobs:
  magento-installation:
    name: Magento ${{ matrix.magento_version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - magento_version: "2.4.9"
            php_image: "yireo/magento2base:8.5"
            search_image: "yireo/opensearch-dummy"
            mysql_image: "mysql:8.0"
            magento_install_args: "--opensearch-host=search"

          - magento_version: "2.4.8-p5"
            php_image: "yireo/magento2base:8.4"
            search_image: "yireo/opensearch-dummy"
            mysql_image: "mysql:8.0"
            magento_install_args: "--opensearch-host=search"
          
          - magento_version: "2.4.8-p3"
            php_image: "yireo/magento2base:8.3"
            search_image: "yireo/opensearch-dummy"
            mysql_image: "mysql:8.0"
            magento_install_args: "--opensearch-host=search"
          
          - magento_version: "2.4.7-p4"
            php_image: "yireo/magento2base:8.3"
            search_image: "yireo/opensearch-dummy"
            mysql_image: "mysql:8.0"
            magento_install_args: "--opensearch-host=search"
          
          - magento_version: "2.4.5-p5"
            php_image: "yireo/magento2base:8.1"
            search_image: "docker.elastic.co/elasticsearch/elasticsearch:7.8.0"
            mysql_image: "mysql:8.0"
            magento_install_args: "--elasticsearch-host=search"

    container: ${{ matrix.php_image }}
    services:
      search:
        image: ${{ matrix.search_image }}
        options: -e="discovery.type=single-node" --health-cmd="curl http://localhost:9200/_cluster/health" --health-interval=10s --health-timeout=5s --health-retries=10
      mysql:
        image: ${{ matrix.mysql_image }}
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: magento2
        options: --tmpfs /tmp:rw --tmpfs /var/lib/mysql:rw --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v2
      - name: Trust GitHub SSH host
        run: |
            mkdir -p ~/.ssh
            ssh-keyscan github.com >> ~/.ssh/known_hosts
      - name: Composer preparation
        env:
            MAGENTO_MARKETPLACE_USERNAME: ${{ secrets.MAGENTO_MARKETPLACE_PUBLIC_KEY }}
            MAGENTO_MARKETPLACE_PASSWORD: ${{ secrets.MAGENTO_MARKETPLACE_PRIVATE_KEY }}
        run: |
            mkdir -p /tmp/m2 && cd /tmp/m2
            composer global config http-basic.repo.magento.com $MAGENTO_MARKETPLACE_USERNAME $MAGENTO_MARKETPLACE_PASSWORD
            composer global config github-oauth.github.com ${{ secrets.GITHUB_TOKEN }}
            composer global config -l
      - name: Creating Magento composer project
        run: |
            MAGENTO_VERSION=${{ matrix.magento_version }}
            test -z "$MAGENTO_VERSION" && exit 1
            composer create-project --repository=https://repo.magento.com/ magento/project-community-edition:${MAGENTO_VERSION} /tmp/m2 --no-install --no-interaction --no-progress
      - name: Setup local composer package
        env:
            COMPOSER_NAME: ${{ secrets.COMPOSER_NAME }}
        run: |
            MAGENTO_VERSION=${{ matrix.magento_version }}
            BRANCH=magento-`echo $MAGENTO_VERSION | cut -f'1-2' -d\.`
            test -z "$MAGENTO_VERSION" && exit 1
            cd /tmp/m2
            composer config audit.block-insecure false
            composer config preferred-install source
            composer config minimum-stability dev
            composer config repositories.remote-source vcs git@github.com:${COMPOSER_NAME}.git
            echo "Installing ${COMPOSER_NAME}:dev-${BRANCH}"
            composer require ${COMPOSER_NAME}:dev-${BRANCH} --no-update --no-interaction
      - name: Composer installation
        run: |
            cd /tmp/m2
            COMPOSER_MEMORY_LIMIT=-1 composer install --prefer-source --no-interaction --no-progress --no-dev
      - name: Magento installation
        run: |
            cd /tmp/m2
            php -d memory_limit=2G bin/magento setup:install --base-url=http://magento2.test/ \
                --db-host=mysql --db-name=magento2 \
                --db-user=root --db-password=root \
                --admin-firstname=John --admin-lastname=Doe \
                --admin-email=johndoe@example.com \
                --admin-user=johndoe --admin-password=johndoe!1234 \
                --backend-frontname=admin --language=en_US \
                --currency=USD --timezone=Europe/Amsterdam --cleanup-database \
                --sales-order-increment-prefix="ORD$" --session-save=db \
                --use-rewrites=1 ${{ matrix.magento_install_args }}
      - name: Magento compilation
        run: |
            cd /tmp/m2
            php -d memory_limit=2G bin/magento setup:di:compile
      - name: Additional checks
        run: |
            cd /tmp/m2
            bin/magento module:status | sort

